//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuarderiaWeb.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioGuarderiaSoap")]
    public interface ServicioGuarderiaSoap {
        
        // CODEGEN: El parámetro 'crudmfacturaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudmfactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudmfacturaResponse crudmfactura(GuarderiaWeb.ServiceReference1.crudmfacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudmfactura", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudmfacturaResponse> crudmfacturaAsync(GuarderiaWeb.ServiceReference1.crudmfacturaRequest request);
        
        // CODEGEN: El parámetro 'crudDetalleAsistenciaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudDetalleAsistencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse crudDetalleAsistencia(GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudDetalleAsistencia", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse> crudDetalleAsistenciaAsync(GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest request);
        
        // CODEGEN: El parámetro 'crudAsistenciaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAsistencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudAsistenciaResponse crudAsistencia(GuarderiaWeb.ServiceReference1.crudAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAsistencia", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAsistenciaResponse> crudAsistenciaAsync(GuarderiaWeb.ServiceReference1.crudAsistenciaRequest request);
        
        // CODEGEN: El parámetro 'crudDetalleConsumosResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudDetalleConsumos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse crudDetalleConsumos(GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudDetalleConsumos", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse> crudDetalleConsumosAsync(GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest request);
        
        // CODEGEN: El parámetro 'crudConsumosResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudConsumos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudConsumosResponse crudConsumos(GuarderiaWeb.ServiceReference1.crudConsumosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudConsumos", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudConsumosResponse> crudConsumosAsync(GuarderiaWeb.ServiceReference1.crudConsumosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudChild", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable crudChild(int IDmatricula, string nombre, string FechaRegistro, string FechaNacimiento, string op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudChild", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> crudChildAsync(int IDmatricula, string nombre, string FechaRegistro, string FechaNacimiento, string op);
        
        // CODEGEN: El parámetro 'crudChildRelationsResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudChildRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudChildRelationsResponse crudChildRelations(GuarderiaWeb.ServiceReference1.crudChildRelationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudChildRelations", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudChildRelationsResponse> crudChildRelationsAsync(GuarderiaWeb.ServiceReference1.crudChildRelationsRequest request);
        
        // CODEGEN: El parámetro 'crudEncargadosResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudEncargados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudEncargadosResponse crudEncargados(GuarderiaWeb.ServiceReference1.crudEncargadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudEncargados", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudEncargadosResponse> crudEncargadosAsync(GuarderiaWeb.ServiceReference1.crudEncargadosRequest request);
        
        // CODEGEN: El parámetro 'crudAbonadoResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAbonado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudAbonadoResponse crudAbonado(GuarderiaWeb.ServiceReference1.crudAbonadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAbonado", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAbonadoResponse> crudAbonadoAsync(GuarderiaWeb.ServiceReference1.crudAbonadoRequest request);
        
        // CODEGEN: El parámetro 'crudAlergiasResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAlergias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudAlergiasResponse crudAlergias(GuarderiaWeb.ServiceReference1.crudAlergiasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudAlergias", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAlergiasResponse> crudAlergiasAsync(GuarderiaWeb.ServiceReference1.crudAlergiasRequest request);
        
        // CODEGEN: El parámetro 'crudMenusResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudMenus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudMenusResponse crudMenus(GuarderiaWeb.ServiceReference1.crudMenusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudMenus", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudMenusResponse> crudMenusAsync(GuarderiaWeb.ServiceReference1.crudMenusRequest request);
        
        // CODEGEN: El parámetro 'crudIngredientesResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudIngredientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudIngredientesResponse crudIngredientes(GuarderiaWeb.ServiceReference1.crudIngredientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudIngredientes", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientesResponse> crudIngredientesAsync(GuarderiaWeb.ServiceReference1.crudIngredientesRequest request);
        
        // CODEGEN: El parámetro 'crudIngredientePlatoResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudIngredientePlato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse crudIngredientePlato(GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudIngredientePlato", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse> crudIngredientePlatoAsync(GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest request);
        
        // CODEGEN: El parámetro 'crudPlatosResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudPlatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudPlatosResponse crudPlatos(GuarderiaWeb.ServiceReference1.crudPlatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudPlatos", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosResponse> crudPlatosAsync(GuarderiaWeb.ServiceReference1.crudPlatosRequest request);
        
        // CODEGEN: El parámetro 'crudPlatosMenuResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudPlatosMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse crudPlatosMenu(GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crudPlatosMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse> crudPlatosMenuAsync(GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudmfactura", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudmfacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDAbonado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FechaCreacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string op;
        
        public crudmfacturaRequest() {
        }
        
        public crudmfacturaRequest(int ID, int IDAbonado, string mes, string FechaCreacion, string op) {
            this.ID = ID;
            this.IDAbonado = IDAbonado;
            this.mes = mes;
            this.FechaCreacion = FechaCreacion;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudmfacturaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudmfacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudmfacturaResult;
        
        public crudmfacturaResponse() {
        }
        
        public crudmfacturaResponse(System.Data.DataTable[] crudmfacturaResult) {
            this.crudmfacturaResult = crudmfacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudDetalleAsistencia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudDetalleAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDFactura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int IDAsistencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FechaCreacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string op;
        
        public crudDetalleAsistenciaRequest() {
        }
        
        public crudDetalleAsistenciaRequest(int ID, int IDFactura, int IDAsistencia, string FechaCreacion, string op) {
            this.ID = ID;
            this.IDFactura = IDFactura;
            this.IDAsistencia = IDAsistencia;
            this.FechaCreacion = FechaCreacion;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudDetalleAsistenciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudDetalleAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudDetalleAsistenciaResult;
        
        public crudDetalleAsistenciaResponse() {
        }
        
        public crudDetalleAsistenciaResponse(System.Data.DataTable[] crudDetalleAsistenciaResult) {
            this.crudDetalleAsistenciaResult = crudDetalleAsistenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAsistencia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idChild;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string FechaRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string horaEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string horaSalida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string detalles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public byte Cancelado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string op;
        
        public crudAsistenciaRequest() {
        }
        
        public crudAsistenciaRequest(int ID, int idChild, string FechaRegistro, string mes, string horaEntrada, string horaSalida, string detalles, byte Cancelado, string op) {
            this.ID = ID;
            this.idChild = idChild;
            this.FechaRegistro = FechaRegistro;
            this.mes = mes;
            this.horaEntrada = horaEntrada;
            this.horaSalida = horaSalida;
            this.detalles = detalles;
            this.Cancelado = Cancelado;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAsistenciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudAsistenciaResult;
        
        public crudAsistenciaResponse() {
        }
        
        public crudAsistenciaResponse(System.Data.DataTable[] crudAsistenciaResult) {
            this.crudAsistenciaResult = crudAsistenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudDetalleConsumos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudDetalleConsumosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDcosumo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int IDfactura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string fechaCreacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string op;
        
        public crudDetalleConsumosRequest() {
        }
        
        public crudDetalleConsumosRequest(int ID, int IDcosumo, int IDfactura, string fechaCreacion, string op) {
            this.ID = ID;
            this.IDcosumo = IDcosumo;
            this.IDfactura = IDfactura;
            this.fechaCreacion = fechaCreacion;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudDetalleConsumosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudDetalleConsumosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudDetalleConsumosResult;
        
        public crudDetalleConsumosResponse() {
        }
        
        public crudDetalleConsumosResponse(System.Data.DataTable[] crudDetalleConsumosResult) {
            this.crudDetalleConsumosResult = crudDetalleConsumosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudConsumos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudConsumosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDChild;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int IDMenu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FechaConsumo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int cancelado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string op;
        
        public crudConsumosRequest() {
        }
        
        public crudConsumosRequest(int ID, int IDChild, int IDMenu, string FechaConsumo, int cancelado, string op) {
            this.ID = ID;
            this.IDChild = IDChild;
            this.IDMenu = IDMenu;
            this.FechaConsumo = FechaConsumo;
            this.cancelado = cancelado;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudConsumosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudConsumosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudConsumosResult;
        
        public crudConsumosResponse() {
        }
        
        public crudConsumosResponse(System.Data.DataTable[] crudConsumosResult) {
            this.crudConsumosResult = crudConsumosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudChildRelations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudChildRelationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDChild;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string TipoRelacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string op;
        
        public crudChildRelationsRequest() {
        }
        
        public crudChildRelationsRequest(int ID, int IDChild, string TipoRelacion, string op) {
            this.ID = ID;
            this.IDChild = IDChild;
            this.TipoRelacion = TipoRelacion;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudChildRelationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudChildRelationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudChildRelationsResult;
        
        public crudChildRelationsResponse() {
        }
        
        public crudChildRelationsResponse(System.Data.DataTable[] crudChildRelationsResult) {
            this.crudChildRelationsResult = crudChildRelationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudEncargados", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudEncargadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDChildRelations;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string DNI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string op;
        
        public crudEncargadosRequest() {
        }
        
        public crudEncargadosRequest(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string op) {
            this.ID = ID;
            this.IDChildRelations = IDChildRelations;
            this.DNI = DNI;
            this.Nombre = Nombre;
            this.Direccion = Direccion;
            this.Telefono = Telefono;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudEncargadosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudEncargadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudEncargadosResult;
        
        public crudEncargadosResponse() {
        }
        
        public crudEncargadosResponse(System.Data.DataTable[] crudEncargadosResult) {
            this.crudEncargadosResult = crudEncargadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAbonado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAbonadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDChildRelations;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string DNI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Banco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string CuentaIBAM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string op;
        
        public crudAbonadoRequest() {
        }
        
        public crudAbonadoRequest(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string Banco, string CuentaIBAM, string op) {
            this.ID = ID;
            this.IDChildRelations = IDChildRelations;
            this.DNI = DNI;
            this.Nombre = Nombre;
            this.Direccion = Direccion;
            this.Telefono = Telefono;
            this.Banco = Banco;
            this.CuentaIBAM = CuentaIBAM;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAbonadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAbonadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudAbonadoResult;
        
        public crudAbonadoResponse() {
        }
        
        public crudAbonadoResponse(System.Data.DataTable[] crudAbonadoResult) {
            this.crudAbonadoResult = crudAbonadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAlergias", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAlergiasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDchild;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string NombreIngrediente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string op;
        
        public crudAlergiasRequest() {
        }
        
        public crudAlergiasRequest(int ID, int IDchild, string NombreIngrediente, string op) {
            this.ID = ID;
            this.IDchild = IDchild;
            this.NombreIngrediente = NombreIngrediente;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudAlergiasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudAlergiasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudAlergiasResult;
        
        public crudAlergiasResponse() {
        }
        
        public crudAlergiasResponse(System.Data.DataTable[] crudAlergiasResult) {
            this.crudAlergiasResult = crudAlergiasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudMenus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudMenusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal Precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string op;
        
        public crudMenusRequest() {
        }
        
        public crudMenusRequest(int ID, string nombre, decimal Precio, string op) {
            this.ID = ID;
            this.nombre = nombre;
            this.Precio = Precio;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudMenusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudMenusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudMenusResult;
        
        public crudMenusResponse() {
        }
        
        public crudMenusResponse(System.Data.DataTable[] crudMenusResult) {
            this.crudMenusResult = crudMenusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudIngredientes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudIngredientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string op;
        
        public crudIngredientesRequest() {
        }
        
        public crudIngredientesRequest(string nombre, string op) {
            this.nombre = nombre;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudIngredientesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudIngredientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudIngredientesResult;
        
        public crudIngredientesResponse() {
        }
        
        public crudIngredientesResponse(System.Data.DataTable[] crudIngredientesResult) {
            this.crudIngredientesResult = crudIngredientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudIngredientePlato", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudIngredientePlatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nombrePlato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nombreIngrediente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string op;
        
        public crudIngredientePlatoRequest() {
        }
        
        public crudIngredientePlatoRequest(int ID, string nombrePlato, string nombreIngrediente, string op) {
            this.ID = ID;
            this.nombrePlato = nombrePlato;
            this.nombreIngrediente = nombreIngrediente;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudIngredientePlatoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudIngredientePlatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudIngredientePlatoResult;
        
        public crudIngredientePlatoResponse() {
        }
        
        public crudIngredientePlatoResponse(System.Data.DataTable[] crudIngredientePlatoResult) {
            this.crudIngredientePlatoResult = crudIngredientePlatoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudPlatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudPlatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string op;
        
        public crudPlatosRequest() {
        }
        
        public crudPlatosRequest(string nombre, string op) {
            this.nombre = nombre;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudPlatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudPlatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudPlatosResult;
        
        public crudPlatosResponse() {
        }
        
        public crudPlatosResponse(System.Data.DataTable[] crudPlatosResult) {
            this.crudPlatosResult = crudPlatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudPlatosMenu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudPlatosMenuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nombrePlato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int IDmenu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string op;
        
        public crudPlatosMenuRequest() {
        }
        
        public crudPlatosMenuRequest(int ID, string nombrePlato, int IDmenu, string op) {
            this.ID = ID;
            this.nombrePlato = nombrePlato;
            this.IDmenu = IDmenu;
            this.op = op;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crudPlatosMenuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class crudPlatosMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataTable")]
        public System.Data.DataTable[] crudPlatosMenuResult;
        
        public crudPlatosMenuResponse() {
        }
        
        public crudPlatosMenuResponse(System.Data.DataTable[] crudPlatosMenuResult) {
            this.crudPlatosMenuResult = crudPlatosMenuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioGuarderiaSoapChannel : GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGuarderiaSoapClient : System.ServiceModel.ClientBase<GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap>, GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap {
        
        public ServicioGuarderiaSoapClient() {
        }
        
        public ServicioGuarderiaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGuarderiaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGuarderiaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGuarderiaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudmfacturaResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudmfactura(GuarderiaWeb.ServiceReference1.crudmfacturaRequest request) {
            return base.Channel.crudmfactura(request);
        }
        
        public System.Data.DataTable[] crudmfactura(int ID, int IDAbonado, string mes, string FechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudmfacturaRequest inValue = new GuarderiaWeb.ServiceReference1.crudmfacturaRequest();
            inValue.ID = ID;
            inValue.IDAbonado = IDAbonado;
            inValue.mes = mes;
            inValue.FechaCreacion = FechaCreacion;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudmfacturaResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudmfactura(inValue);
            return retVal.crudmfacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudmfacturaResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudmfacturaAsync(GuarderiaWeb.ServiceReference1.crudmfacturaRequest request) {
            return base.Channel.crudmfacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudmfacturaResponse> crudmfacturaAsync(int ID, int IDAbonado, string mes, string FechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudmfacturaRequest inValue = new GuarderiaWeb.ServiceReference1.crudmfacturaRequest();
            inValue.ID = ID;
            inValue.IDAbonado = IDAbonado;
            inValue.mes = mes;
            inValue.FechaCreacion = FechaCreacion;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudmfacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudDetalleAsistencia(GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest request) {
            return base.Channel.crudDetalleAsistencia(request);
        }
        
        public System.Data.DataTable[] crudDetalleAsistencia(int ID, int IDFactura, int IDAsistencia, string FechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest inValue = new GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest();
            inValue.ID = ID;
            inValue.IDFactura = IDFactura;
            inValue.IDAsistencia = IDAsistencia;
            inValue.FechaCreacion = FechaCreacion;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudDetalleAsistencia(inValue);
            return retVal.crudDetalleAsistenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudDetalleAsistenciaAsync(GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest request) {
            return base.Channel.crudDetalleAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaResponse> crudDetalleAsistenciaAsync(int ID, int IDFactura, int IDAsistencia, string FechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest inValue = new GuarderiaWeb.ServiceReference1.crudDetalleAsistenciaRequest();
            inValue.ID = ID;
            inValue.IDFactura = IDFactura;
            inValue.IDAsistencia = IDAsistencia;
            inValue.FechaCreacion = FechaCreacion;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudDetalleAsistenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudAsistenciaResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAsistencia(GuarderiaWeb.ServiceReference1.crudAsistenciaRequest request) {
            return base.Channel.crudAsistencia(request);
        }
        
        public System.Data.DataTable[] crudAsistencia(int ID, int idChild, string FechaRegistro, string mes, string horaEntrada, string horaSalida, string detalles, byte Cancelado, string op) {
            GuarderiaWeb.ServiceReference1.crudAsistenciaRequest inValue = new GuarderiaWeb.ServiceReference1.crudAsistenciaRequest();
            inValue.ID = ID;
            inValue.idChild = idChild;
            inValue.FechaRegistro = FechaRegistro;
            inValue.mes = mes;
            inValue.horaEntrada = horaEntrada;
            inValue.horaSalida = horaSalida;
            inValue.detalles = detalles;
            inValue.Cancelado = Cancelado;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudAsistenciaResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAsistencia(inValue);
            return retVal.crudAsistenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAsistenciaResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAsistenciaAsync(GuarderiaWeb.ServiceReference1.crudAsistenciaRequest request) {
            return base.Channel.crudAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAsistenciaResponse> crudAsistenciaAsync(int ID, int idChild, string FechaRegistro, string mes, string horaEntrada, string horaSalida, string detalles, byte Cancelado, string op) {
            GuarderiaWeb.ServiceReference1.crudAsistenciaRequest inValue = new GuarderiaWeb.ServiceReference1.crudAsistenciaRequest();
            inValue.ID = ID;
            inValue.idChild = idChild;
            inValue.FechaRegistro = FechaRegistro;
            inValue.mes = mes;
            inValue.horaEntrada = horaEntrada;
            inValue.horaSalida = horaSalida;
            inValue.detalles = detalles;
            inValue.Cancelado = Cancelado;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAsistenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudDetalleConsumos(GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest request) {
            return base.Channel.crudDetalleConsumos(request);
        }
        
        public System.Data.DataTable[] crudDetalleConsumos(int ID, int IDcosumo, int IDfactura, string fechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest inValue = new GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest();
            inValue.ID = ID;
            inValue.IDcosumo = IDcosumo;
            inValue.IDfactura = IDfactura;
            inValue.fechaCreacion = fechaCreacion;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudDetalleConsumos(inValue);
            return retVal.crudDetalleConsumosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudDetalleConsumosAsync(GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest request) {
            return base.Channel.crudDetalleConsumosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudDetalleConsumosResponse> crudDetalleConsumosAsync(int ID, int IDcosumo, int IDfactura, string fechaCreacion, string op) {
            GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest inValue = new GuarderiaWeb.ServiceReference1.crudDetalleConsumosRequest();
            inValue.ID = ID;
            inValue.IDcosumo = IDcosumo;
            inValue.IDfactura = IDfactura;
            inValue.fechaCreacion = fechaCreacion;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudDetalleConsumosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudConsumosResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudConsumos(GuarderiaWeb.ServiceReference1.crudConsumosRequest request) {
            return base.Channel.crudConsumos(request);
        }
        
        public System.Data.DataTable[] crudConsumos(int ID, int IDChild, int IDMenu, string FechaConsumo, int cancelado, string op) {
            GuarderiaWeb.ServiceReference1.crudConsumosRequest inValue = new GuarderiaWeb.ServiceReference1.crudConsumosRequest();
            inValue.ID = ID;
            inValue.IDChild = IDChild;
            inValue.IDMenu = IDMenu;
            inValue.FechaConsumo = FechaConsumo;
            inValue.cancelado = cancelado;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudConsumosResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudConsumos(inValue);
            return retVal.crudConsumosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudConsumosResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudConsumosAsync(GuarderiaWeb.ServiceReference1.crudConsumosRequest request) {
            return base.Channel.crudConsumosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudConsumosResponse> crudConsumosAsync(int ID, int IDChild, int IDMenu, string FechaConsumo, int cancelado, string op) {
            GuarderiaWeb.ServiceReference1.crudConsumosRequest inValue = new GuarderiaWeb.ServiceReference1.crudConsumosRequest();
            inValue.ID = ID;
            inValue.IDChild = IDChild;
            inValue.IDMenu = IDMenu;
            inValue.FechaConsumo = FechaConsumo;
            inValue.cancelado = cancelado;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudConsumosAsync(inValue);
        }
        
        public System.Data.DataTable crudChild(int IDmatricula, string nombre, string FechaRegistro, string FechaNacimiento, string op) {
            return base.Channel.crudChild(IDmatricula, nombre, FechaRegistro, FechaNacimiento, op);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> crudChildAsync(int IDmatricula, string nombre, string FechaRegistro, string FechaNacimiento, string op) {
            return base.Channel.crudChildAsync(IDmatricula, nombre, FechaRegistro, FechaNacimiento, op);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudChildRelationsResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudChildRelations(GuarderiaWeb.ServiceReference1.crudChildRelationsRequest request) {
            return base.Channel.crudChildRelations(request);
        }
        
        public System.Data.DataTable[] crudChildRelations(int ID, int IDChild, string TipoRelacion, string op) {
            GuarderiaWeb.ServiceReference1.crudChildRelationsRequest inValue = new GuarderiaWeb.ServiceReference1.crudChildRelationsRequest();
            inValue.ID = ID;
            inValue.IDChild = IDChild;
            inValue.TipoRelacion = TipoRelacion;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudChildRelationsResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudChildRelations(inValue);
            return retVal.crudChildRelationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudChildRelationsResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudChildRelationsAsync(GuarderiaWeb.ServiceReference1.crudChildRelationsRequest request) {
            return base.Channel.crudChildRelationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudChildRelationsResponse> crudChildRelationsAsync(int ID, int IDChild, string TipoRelacion, string op) {
            GuarderiaWeb.ServiceReference1.crudChildRelationsRequest inValue = new GuarderiaWeb.ServiceReference1.crudChildRelationsRequest();
            inValue.ID = ID;
            inValue.IDChild = IDChild;
            inValue.TipoRelacion = TipoRelacion;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudChildRelationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudEncargadosResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudEncargados(GuarderiaWeb.ServiceReference1.crudEncargadosRequest request) {
            return base.Channel.crudEncargados(request);
        }
        
        public System.Data.DataTable[] crudEncargados(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string op) {
            GuarderiaWeb.ServiceReference1.crudEncargadosRequest inValue = new GuarderiaWeb.ServiceReference1.crudEncargadosRequest();
            inValue.ID = ID;
            inValue.IDChildRelations = IDChildRelations;
            inValue.DNI = DNI;
            inValue.Nombre = Nombre;
            inValue.Direccion = Direccion;
            inValue.Telefono = Telefono;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudEncargadosResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudEncargados(inValue);
            return retVal.crudEncargadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudEncargadosResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudEncargadosAsync(GuarderiaWeb.ServiceReference1.crudEncargadosRequest request) {
            return base.Channel.crudEncargadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudEncargadosResponse> crudEncargadosAsync(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string op) {
            GuarderiaWeb.ServiceReference1.crudEncargadosRequest inValue = new GuarderiaWeb.ServiceReference1.crudEncargadosRequest();
            inValue.ID = ID;
            inValue.IDChildRelations = IDChildRelations;
            inValue.DNI = DNI;
            inValue.Nombre = Nombre;
            inValue.Direccion = Direccion;
            inValue.Telefono = Telefono;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudEncargadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudAbonadoResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAbonado(GuarderiaWeb.ServiceReference1.crudAbonadoRequest request) {
            return base.Channel.crudAbonado(request);
        }
        
        public System.Data.DataTable[] crudAbonado(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string Banco, string CuentaIBAM, string op) {
            GuarderiaWeb.ServiceReference1.crudAbonadoRequest inValue = new GuarderiaWeb.ServiceReference1.crudAbonadoRequest();
            inValue.ID = ID;
            inValue.IDChildRelations = IDChildRelations;
            inValue.DNI = DNI;
            inValue.Nombre = Nombre;
            inValue.Direccion = Direccion;
            inValue.Telefono = Telefono;
            inValue.Banco = Banco;
            inValue.CuentaIBAM = CuentaIBAM;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudAbonadoResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAbonado(inValue);
            return retVal.crudAbonadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAbonadoResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAbonadoAsync(GuarderiaWeb.ServiceReference1.crudAbonadoRequest request) {
            return base.Channel.crudAbonadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAbonadoResponse> crudAbonadoAsync(int ID, int IDChildRelations, string DNI, string Nombre, string Direccion, string Telefono, string Banco, string CuentaIBAM, string op) {
            GuarderiaWeb.ServiceReference1.crudAbonadoRequest inValue = new GuarderiaWeb.ServiceReference1.crudAbonadoRequest();
            inValue.ID = ID;
            inValue.IDChildRelations = IDChildRelations;
            inValue.DNI = DNI;
            inValue.Nombre = Nombre;
            inValue.Direccion = Direccion;
            inValue.Telefono = Telefono;
            inValue.Banco = Banco;
            inValue.CuentaIBAM = CuentaIBAM;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAbonadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudAlergiasResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAlergias(GuarderiaWeb.ServiceReference1.crudAlergiasRequest request) {
            return base.Channel.crudAlergias(request);
        }
        
        public System.Data.DataTable[] crudAlergias(int ID, int IDchild, string NombreIngrediente, string op) {
            GuarderiaWeb.ServiceReference1.crudAlergiasRequest inValue = new GuarderiaWeb.ServiceReference1.crudAlergiasRequest();
            inValue.ID = ID;
            inValue.IDchild = IDchild;
            inValue.NombreIngrediente = NombreIngrediente;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudAlergiasResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAlergias(inValue);
            return retVal.crudAlergiasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAlergiasResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudAlergiasAsync(GuarderiaWeb.ServiceReference1.crudAlergiasRequest request) {
            return base.Channel.crudAlergiasAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudAlergiasResponse> crudAlergiasAsync(int ID, int IDchild, string NombreIngrediente, string op) {
            GuarderiaWeb.ServiceReference1.crudAlergiasRequest inValue = new GuarderiaWeb.ServiceReference1.crudAlergiasRequest();
            inValue.ID = ID;
            inValue.IDchild = IDchild;
            inValue.NombreIngrediente = NombreIngrediente;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudAlergiasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudMenusResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudMenus(GuarderiaWeb.ServiceReference1.crudMenusRequest request) {
            return base.Channel.crudMenus(request);
        }
        
        public System.Data.DataTable[] crudMenus(int ID, string nombre, decimal Precio, string op) {
            GuarderiaWeb.ServiceReference1.crudMenusRequest inValue = new GuarderiaWeb.ServiceReference1.crudMenusRequest();
            inValue.ID = ID;
            inValue.nombre = nombre;
            inValue.Precio = Precio;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudMenusResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudMenus(inValue);
            return retVal.crudMenusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudMenusResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudMenusAsync(GuarderiaWeb.ServiceReference1.crudMenusRequest request) {
            return base.Channel.crudMenusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudMenusResponse> crudMenusAsync(int ID, string nombre, decimal Precio, string op) {
            GuarderiaWeb.ServiceReference1.crudMenusRequest inValue = new GuarderiaWeb.ServiceReference1.crudMenusRequest();
            inValue.ID = ID;
            inValue.nombre = nombre;
            inValue.Precio = Precio;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudMenusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudIngredientesResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudIngredientes(GuarderiaWeb.ServiceReference1.crudIngredientesRequest request) {
            return base.Channel.crudIngredientes(request);
        }
        
        public System.Data.DataTable[] crudIngredientes(string nombre, string op) {
            GuarderiaWeb.ServiceReference1.crudIngredientesRequest inValue = new GuarderiaWeb.ServiceReference1.crudIngredientesRequest();
            inValue.nombre = nombre;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudIngredientesResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudIngredientes(inValue);
            return retVal.crudIngredientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientesResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudIngredientesAsync(GuarderiaWeb.ServiceReference1.crudIngredientesRequest request) {
            return base.Channel.crudIngredientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientesResponse> crudIngredientesAsync(string nombre, string op) {
            GuarderiaWeb.ServiceReference1.crudIngredientesRequest inValue = new GuarderiaWeb.ServiceReference1.crudIngredientesRequest();
            inValue.nombre = nombre;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudIngredientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudIngredientePlato(GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest request) {
            return base.Channel.crudIngredientePlato(request);
        }
        
        public System.Data.DataTable[] crudIngredientePlato(int ID, string nombrePlato, string nombreIngrediente, string op) {
            GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest inValue = new GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest();
            inValue.ID = ID;
            inValue.nombrePlato = nombrePlato;
            inValue.nombreIngrediente = nombreIngrediente;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudIngredientePlato(inValue);
            return retVal.crudIngredientePlatoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudIngredientePlatoAsync(GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest request) {
            return base.Channel.crudIngredientePlatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudIngredientePlatoResponse> crudIngredientePlatoAsync(int ID, string nombrePlato, string nombreIngrediente, string op) {
            GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest inValue = new GuarderiaWeb.ServiceReference1.crudIngredientePlatoRequest();
            inValue.ID = ID;
            inValue.nombrePlato = nombrePlato;
            inValue.nombreIngrediente = nombreIngrediente;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudIngredientePlatoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudPlatosResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudPlatos(GuarderiaWeb.ServiceReference1.crudPlatosRequest request) {
            return base.Channel.crudPlatos(request);
        }
        
        public System.Data.DataTable[] crudPlatos(string nombre, string op) {
            GuarderiaWeb.ServiceReference1.crudPlatosRequest inValue = new GuarderiaWeb.ServiceReference1.crudPlatosRequest();
            inValue.nombre = nombre;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudPlatosResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudPlatos(inValue);
            return retVal.crudPlatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudPlatosAsync(GuarderiaWeb.ServiceReference1.crudPlatosRequest request) {
            return base.Channel.crudPlatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosResponse> crudPlatosAsync(string nombre, string op) {
            GuarderiaWeb.ServiceReference1.crudPlatosRequest inValue = new GuarderiaWeb.ServiceReference1.crudPlatosRequest();
            inValue.nombre = nombre;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudPlatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudPlatosMenu(GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest request) {
            return base.Channel.crudPlatosMenu(request);
        }
        
        public System.Data.DataTable[] crudPlatosMenu(int ID, string nombrePlato, int IDmenu, string op) {
            GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest inValue = new GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest();
            inValue.ID = ID;
            inValue.nombrePlato = nombrePlato;
            inValue.IDmenu = IDmenu;
            inValue.op = op;
            GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse retVal = ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudPlatosMenu(inValue);
            return retVal.crudPlatosMenuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse> GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap.crudPlatosMenuAsync(GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest request) {
            return base.Channel.crudPlatosMenuAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuarderiaWeb.ServiceReference1.crudPlatosMenuResponse> crudPlatosMenuAsync(int ID, string nombrePlato, int IDmenu, string op) {
            GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest inValue = new GuarderiaWeb.ServiceReference1.crudPlatosMenuRequest();
            inValue.ID = ID;
            inValue.nombrePlato = nombrePlato;
            inValue.IDmenu = IDmenu;
            inValue.op = op;
            return ((GuarderiaWeb.ServiceReference1.ServicioGuarderiaSoap)(this)).crudPlatosMenuAsync(inValue);
        }
    }
}
